export const SET_CURRENT_MODE = "SET_CURRENT_MODE";
export const SET_CURRENT_FORECAST = "SET_CURRENT_FORECAST";
export const SET_LOCATION = "SET_LOCATION";
export const SET_SEARCH_RESULT = "SET_SEARCH_RESULT";
export const SET_ASTRO_DATA = "SET_ASTRO_DATA";
export const SET_WEEKDAYS_FORECAST = "SET_WEEKDAYS_FORECAST";
export const SET_DEGREE = "SET_DEGREE";
